Repository hellicopthecat/project-manazoo, pull requests merged in 2025-09, with the labels that each got.

#48 47-animal-repository
  src/app/animal/AnimalManager.java
  src/app/repository/MemoryAnimalRepository.java
  src/app/repository/interfaces/AnimalRepository.java
Labels: enhancement, refactor

#50 49 configure GitHub reviewer
  .github/copilot-instructions.md
  .github/pull_request_template.md
Labels: enhancement

#51 main -> develop merge (Configure Reviewer)
  .github/copilot-instructions.md
  .github/pull_request_template.md
Labels: documentation

#53 Revert "Revert "47-animal-repository""
  src/app/animal/AnimalManager.java
  src/app/repository/MemoryAnimalRepository.java
  src/app/repository/interfaces/AnimalRepository.java
Labels: enhancement, refactor

#56 55 visitor repository
  src/app/repository/MemoryVisitorRepository.java
  src/app/repository/interfaces/VisitorRepository.java
  src/app/visitor/VisitorManager.java
Labels: enhancement, refactor

#58 refactor: FinanceManager에 Repository 패턴 적용
  src/app/finance/FinanceManager.java
  src/app/incomeExpend/IncomeExpend.java
  src/app/repository/interfaces/IncomeExpendRepository.java
  src/app/repository/memory/MemoryIncomeExpendRepository.java
Labels: enhancement, refactor

#61 Develop --> Main merge
  src/app/animal/AnimalManager.java
  src/app/enclosure/Enclosure.java
  src/app/enclosure/EnclosureManager.java
  src/app/finance/FinanceManager.java
  src/app/incomeExpend/IncomeExpend.java
  src/app/repository/MemoryAnimalRepository.java
  src/app/repository/MemoryEnclosureRepository.java
  src/app/repository/MemoryVisitorRepository.java
  src/app/repository/MemoryZooKeeperRepository.java
  src/app/repository/interfaces/AnimalRepository.java
  src/app/repository/interfaces/EnclosureRepository.java
  src/app/repository/interfaces/IncomeExpendRepository.java
  src/app/repository/interfaces/Repository.java
  src/app/repository/interfaces/VisitorRepository.java
  src/app/repository/interfaces/ZooKeeperRepository.java
  src/app/repository/memory/MemoryIncomeExpendRepository.java
  src/app/visitor/VisitorManager.java
  src/app/zooKeeper/ZooKeeperManager.java
Labels: help wanted

#68 refactor: repository 적용 미진한 부분 수정
  src/app/console/ConsoleEngine.java
  src/app/enclosure/Enclosure.java
  src/app/enclosure/EnclosureInterface.java
  src/app/zooKeeper/ZooKeeperManager.java
  src/app/zooKeeper/ZooKeeperRepository.java
Labels: enhancement, refactor

#73 fix: sequence bug
  src/app/enclosure/EnclosureManager.java
Labels: bug

#66 64 animal UI refactor
  src/app/animal/Animal.java
  src/app/animal/AnimalEnum.java
  src/app/animal/AnimalManager.java
  src/app/common/InputUtil.java
  src/app/console/ConsoleEngine.java
  src/app/repository/MemoryAnimalRepository.java
  src/app/repository/interfaces/AnimalRepository.java
  src/app/visitor/VisitorManager.java
Labels: enhancement, refactor

#76 Merge Develop To Main
  src/app/Main.java
  src/app/animal/Animal.java
  src/app/animal/AnimalEnum.java
  src/app/animal/AnimalManager.java
  src/app/common/InputUtil.java
  src/app/common/ui/MenuUtil.java
  src/app/common/ui/TableUtil.java
  src/app/console/ConsoleEngine.java
  src/app/enclosure/Enclosure.java
  src/app/enclosure/EnclosureInterface.java
  src/app/enclosure/EnclosureManager.java
  src/app/finance/FinanceManager.java
  src/app/incomeExpend/IEConverter.java
  src/app/repository/MemoryAnimalRepository.java
  src/app/repository/MemoryEnclosureRepository.java
  src/app/repository/MemoryVisitorRepository.java
  src/app/repository/MemoryZooKeeperRepository.java
  src/app/repository/interfaces/AnimalRepository.java
  src/app/repository/interfaces/ZooKeeperRepository.java
  src/app/repository/memory/MemoryIncomeExpendRepository.java
  src/app/visitor/Reservation.java
  src/app/visitor/VisitorManager.java
  src/app/zooKeeper/ZooKeeper.java
  src/app/zooKeeper/ZooKeeperManager.java
  src/app/zooKeeper/ZooKeeperRepository.java
  src/app/zooKeeper/zooKeeperEnum/ZooKeeperConverter.java
Labels: documentation

#77 feat: create JDBC repository config
  .gitignore
  config/database.properties.template
  src/app/config/DatabaseConfigLoader.java
  src/app/config/DatabaseConnection.java
  src/module-info.java
Labels: feature

#91 85 jdbc reservation repository
  create_db.sql
  insert_db.sql
  src/app/repository/jdbc/JdbcVisitorRepository.java
  src/app/visitor/VisitorManager.java
Labels: enhancement, feature

#92 86 jdbc incomeexpend repository
  src/app/finance/FinanceManager.java
  src/app/incomeExpend/IEConverter.java
  src/app/incomeExpend/IncomeExpend.java
  src/app/incomeExpend/IncomeExpendType.java
  src/app/repository/jdbc/JdbcIncomeExpendRepository.java
  src/app/repository/memory/MemoryIncomeExpendRepository.java
Labels: enhancement, feature

#90 82 jdbc animal repository
  src/app/animal/AnimalManager.java
  src/app/common/ui/MenuUtil.java
  src/app/config/DatabaseConnection.java
  src/app/console/ConsoleEngine.java
  src/app/repository/JdbcAnimalRepository.java
Labels: enhancement, refactor, feature

#94 84 jdbc zookeeper repository
  create_db.sql
  insert_db.sql
  src/app/finance/FinanceManager.java
  src/app/repository/jdbc/JdbcIncomeExpendRepository.java
  src/app/repository/jdbc/JdbcZooKeeperRepository.java
  src/app/zooKeeper/ZooKeeper.java
  src/app/zooKeeper/ZooKeeperManager.java
Labels: enhancement, feature

#108 feat: 트랜잭션 매니저와 커넥션 풀 도입 (1-2단계 인프라)
  src/app/common/database/ConnectionPool.java
  src/app/common/transaction/JdbcTransactionManager.java
  src/app/common/transaction/TransactionManager.java
  src/app/common/transaction/TransactionTemplate.java
  src/app/controller/sample/SampleAnimalController.java
Labels: enhancement, feature
