Repository hellicopthecat/project-manazoo, pull requests merged in 2025-08, with the labels that each got.

#15 feat: github PR template
  .github/pull_request_template.md
Labels: enhancement

#10 Animal 완성
  src/app/animal/Animal.java
  src/app/animal/AnimalEnum.java
  src/app/animal/AnimalManager.java
Labels: enhancement

#18 8 UI enhancement
  src/app/common/ui/MenuUtil.java
  src/app/common/ui/TableUtil.java
  src/app/common/ui/TextArtUtil.java
  src/app/common/ui/UIUtil.java
  src/app/console/ConsoleEngine.java
  src/app/enclosure/EnclosureManager.java
Labels: enhancement, feature

#23 Visitor class
  src/app/animal/AnimalManager.java
  src/app/common/IdGeneratorUtil.java
  src/app/visitor/Reservation.java
  src/app/visitor/Visitor.java
  src/app/visitor/VisitorManager.java
Labels: enhancement

#27 📝 Refactor : Edit package path & Remove duplicate code
  src/app/animal/AnimalManager.java
  src/app/common/IdGeneratorUtil.java
  src/app/visitor/VisitorManager.java
Labels: documentation, refactor

#35 UI zookeeper & Finance
  src/app/finance/FinanceManager.java
  src/app/incomeExpend/IncomeExpend.java
  src/app/zooKeeper/ZooKeeper.java
  src/app/zooKeeper/ZooKeeperManager.java
  src/app/zooKeeper/ZooKeeperRepository.java
Labels: documentation, refactor

#34 25 enclosure register enhance
  src/app/animal/AnimalManager.java
  src/app/common/ui/TextArtUtil.java
  src/app/console/ConsoleEngine.java
  src/app/enclosure/Enclosure.java
  src/app/enclosure/EnclosureInterface.java
  src/app/enclosure/EnclosureManager.java
Labels: enhancement, refactor, feature

#44 refactor: EnclosureManager에 Repository 패턴 적용
  src/app/enclosure/Enclosure.java
  src/app/enclosure/EnclosureManager.java
  src/app/repository/MemoryEnclosureRepository.java
  src/app/repository/interfaces/EnclosureRepository.java
  src/app/repository/interfaces/Repository.java
Labels: enhancement, refactor
